server.port=8080
spring.application.name=evcharging

# ===============================
# H2 In-Memory Database Datasource
# ===============================
spring.datasource.url=jdbc:h2:mem:ev_charging;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ===============================
# Enable H2 Console
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
